config/routes.rb
Rails.application.routes.draw do


  apipie
  root to: 'admin/home#index'

  devise_for :users, 
             controllers: { sessions: "users/sessions" }, 
             path: "", 
             path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

  #menu 
    resources :menus, path: 'menu', except: :new do
        #add a category under super category.
        get 'new', to: 'menus#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

  #banner
    resources :banners, path: 'banner'
  #links
    resources :links, path: 'link'


  #article module
    resources :categories, path: 'category', except: :new do
        #add a category under super category.
        get 'new', to: 'categories#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

    resources :articles, path: 'article' do
        #reload article elements when categroy select changed.
        get 'concat', to: 'articles#article_concat', on: :collection
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
    end
    resources :article_options, path: 'article-option'
    resources :article_pictures, path: 'article-picture', only: [:create, :destroy] do
      #show pictures belongs specificy article.
      get '',  to: 'article_pictures#index', 
               as: :picture_by, 
               constraints: { article_id: /\d/ },
               on: :member  
    end
  #album module
    resources :album_tags, path: 'album-tags'
    resources :albums
    resources :photos, except: :new do
      get 'new', to: 'photos#new', 
                 as: :photo_new, 
                 :constraints => { :parent_id => /\d|nil/ },
                 on: :member
    end

  #page module
    resources :pages, path: 'page'
    
  #trash module
    namespace :trash do
      #for article
      resources :articles, path: 'article', only: [:index, :destroy] do
        put 'restore', to: 'articles#restore', on: :member
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
      end
      #for pages
      resources :pages, path: 'page', only: [:index, :destroy] do
        put 'restore', to: 'pages#restore', on: :member
      end
    end
    #end trash namespae
    
    #message module
    resources :messages, path: 'message' do
      put 'review', to: 'messages#review', on: :member
    end

    get 'visit', to: 'statistics#index', as: 'visit'

  end 
  #end admin namespace

   namespace :api do
      # api for layouts
      get 'menus',                 to: 'layouts#menus'
      get 'link',                  to: 'layouts#friend_links'
      get 'categories',            to: 'categories#index'
      get 'category/:id',          to: 'categories#show'
      get 'articles',              to: 'articles#index'
      get 'article/:id',           to: 'articles#show'
      get 'articles/title/:title', to: 'articles#search_by_title'
   end

   get 'home',        to: 'home/index#index'
   get 'news',        to: 'home/article#news'
   get 'notices',     to: 'home/article#notices'
   get 'products',    to: 'home/article#products'
   get 'article/:id', to: 'home/article#show',    as: 'article'
   get 'product/:id', to: 'home/article#product', as: 'product'
   get 'albums',      to: 'home/album#list',      as: 'albums'
   get 'album/:id',   to: 'home/album#show',      as: 'album'
   get 'about-us',    to: 'home/page#about_us'
   get 'contract-us', to: 'home/page#contract_us'

end

app/views/admin/pages/_form.html.erb
<% if @admin_page.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger fade in">
    <button class="close" data-dismiss="alert">×</button>
    <i class="fa-fw fa fa-times"></i>
    <strong>
      <% @admin_page.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    </strong>
  </div>
</div>
<% end %>
<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
  <header>
    <span class="widget-icon"><i class="fa fa-edit"></i></span>
    <h2><%= t "page.edit_title" %></h2>
  </header>
  <div>
    <div class="jarviswidget-editbox"></div>  
    <div class="widget-body no-padding">
      <%= form_for(@admin_page, html: { class: "smart-form", id: "validate-form" }) do |f| %>
      <fieldset>
        
        <div class="row">
          <section class="col col-8">
            <label class="label"> 
              <%= f.label t "page.title" %><br>
            </label>
            <label class="input">
              <i class="icon-append fa fa-pencil"></i>
              <%= f.text_field :title, required: true, maxlength: 26 %>
            </label>
          </section>
        </div>

        <div class="row">
          <section class="col col-8"> 
            <label class="label"><%= f.label t "page.abstract"  %><br></label>
            <label class="textarea textarea-resizable"><i class="icon-append fa fa-comment"></i>   
              <%= f.text_area :abstract, class: "custom-scroll", rows: "7" %>                
            </label>
          </section>
        </div>
        
        <div class="row">
          <section class="col col-8"> 
            <label class="label"><%= f.label t "page.content"  %><br></label>
            <%= f.cktext_area :content, required: true, :ckeditor => {:language => 'zh-cn', :toolbar => 'Full' }  %>
          </section>
        </div>

        <footer>
            <%= link_to '返回', admin_pages_path, class: "btn btn-primary" %>
          <div class="actions">
            <%= f.submit '提交', class: "btn btn-primary" %>
          </div>
        </footer>
      </fieldset>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/pages/edit.html.erb
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<%if notice %>
<div class="alert alert-success fade in">
  <button class="close" data-dismiss="alert">×</button>
  <i class="fa-fw fa fa-check"></i>
  <strong><%= notice %></strong>
</div>
<% end %>

<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
  <header>
    <span class="widget-icon"> <i class="fa fa-file"></i> </span>
    <h2><p><%= t "page.table_title" %></p></h2>
  </header>
  <div>
    <div class="jarviswidget-editbox"></div>  
    <div class="widget-body no-padding">
      <table id="datatable_fixed_column" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th><%= t "page.id" %></th>
            <th><%= t "page.title" %></th>
            <th><%= t "page.abstract" %></th>
            <th><%= t "article.created_at" %></th>
            <th><%= t "operate.title" %></th>
          </tr>
             <tr class="second">
            <td class="smart-form">
              <label class="input">
                <input type="text" value="<%= t "page.search_by_id" %>" class="search_init">
              </label>
            </td>
            <td class="smart-form">
              <label class="input">
                <input type="text" value="<%= t "page.search_by_title" %>" class="search_init">
              </label>  
            </td>
            <td class="smart-form">
              <label class="input">
                <input type="text" value="<%= t "page.search_by_content" %>" class="search_init">
              </label>  
            </td>
            <td class="smart-form">
              <label class="input"><i class="icon-append fa fa-calendar"></i>
                <input type="text" value="<%= t "page.search_by_created" %>" class="datepicker search_init" data-dateformat="yy-mm-dd">
              </label>  
            </td>
            <td>
                <%= link_to t("operate.new"), new_admin_page_path, data: { no_turbolink: true }, class: "btn bg-color-green txt-color-white" %>
            </td>
          </tr>
        </thead>

        <tbody>
          <% @admin_pages.each do |admin_page| %>
          <tr>
           <td><%= admin_page.id %></td>
           <td><%= admin_page.title%></td>
            <td> <!-- 这里需要一个判断 -->
              <% if admin_page.abstract %>
              <%= h truncate(admin_page.abstract, length: 45) %>
              <% else %>
              <%= h truncate((admin_page.content), length: 20)  %>
              <% end %>
            </td>
            <td><%= admin_page.created_at.strftime("%Y-%m-%d, %H:%m") %></td>
            <td>
              <%= link_to t("operate.show"), admin_page, class: "btn bg-color-blue txt-color-white" %>
              <%= link_to t("operate.edit"), edit_admin_page_path(admin_page), data: { no_turbolink: true }, class: "btn bg-color-orange txt-color-white" %>
             <%= link_to t("operate.delete"), admin_page, method: :delete, data: { title: "#{t('page.delete_title')}", confirm: "#{t('page.delete_info')}" }, class: "btn bg-color-red txt-color-white" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>      
    </div>
  </div>
</div>

app/views/admin/pages/new.html.erb
<%= render 'form' %>

app/views/admin/pages/show.html.erb
<%if notice %>
<div class="alert alert-success fade in">
  <button class="close" data-dismiss="alert">×</button>
  <i class="fa-fw fa fa-check"></i>
  <strong><%= notice %></strong>
</div>
<% end %>
<div class="jarviswidget jarviswidget-color-darken" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
  <header>
    <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
    <h2><%= t("operate.show") %></h2>        
  </header>
  <div>
    <div class="jarviswidget-editbox"></div>
    <div class="widget-body">
      <div class="smart-form">
        <fieldset>
        	<div class="row">
        		<h2 class="text-center">
        			<%= @admin_page.title %>
        		</h2>
        	</div>
			<div class="row">
				<%= sanitize @admin_page.content %>
			</div>
      <br>
      <br> <!-- <br> for newline -->
        </fieldset>

        <footer>
          <%= link_to t("operate.back"), admin_pages_path, class: "pull-right btn btn-primary" %>
          <%= link_to t("operate.edit"), edit_admin_page_path(@admin_page), class: "pull-right btn btn-primary", data: { no_turbolink: true }%>
        </footer>
      </div>
    </div>
    <!-- end widget content -->
  </div>
  <!-- end widget div -->
</div>