config/routes.rb
Rails.application.routes.draw do


  apipie
  root to: 'admin/home#index'

  devise_for :users, 
             controllers: { sessions: "users/sessions" }, 
             path: "", 
             path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

  #menu 
    resources :menus, path: 'menu', except: :new do
        #add a category under super category.
        get 'new', to: 'menus#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

  #banner
    resources :banners, path: 'banner'
  #links
    resources :links, path: 'link'


  #article module
    resources :categories, path: 'category', except: :new do
        #add a category under super category.
        get 'new', to: 'categories#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

    resources :articles, path: 'article' do
        #reload article elements when categroy select changed.
        get 'concat', to: 'articles#article_concat', on: :collection
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
    end
    resources :article_options, path: 'article-option'
    resources :article_pictures, path: 'article-picture', only: [:create, :destroy] do
      #show pictures belongs specificy article.
      get '',  to: 'article_pictures#index', 
               as: :picture_by, 
               constraints: { article_id: /\d/ },
               on: :member  
    end
  #album module
    resources :album_tags, path: 'album-tags'
    resources :albums
    resources :photos, except: :new do
      get 'new', to: 'photos#new', 
                 as: :photo_new, 
                 :constraints => { :parent_id => /\d|nil/ },
                 on: :member
    end

  #page module
    resources :pages, path: 'page'
    
  #trash module
    namespace :trash do
      #for article
      resources :articles, path: 'article', only: [:index, :destroy] do
        put 'restore', to: 'articles#restore', on: :member
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
      end
      #for pages
      resources :pages, path: 'page', only: [:index, :destroy] do
        put 'restore', to: 'pages#restore', on: :member
      end
    end
    #end trash namespae
    
    #message module
    resources :messages, path: 'message' do
      put 'review', to: 'messages#review', on: :member
    end

    get 'visit', to: 'statistics#index', as: 'visit'

  end 
  #end admin namespace

   namespace :api do
      # api for layouts
      get 'menus',                 to: 'layouts#menus'
      get 'link',                  to: 'layouts#friend_links'
      get 'categories',            to: 'categories#index'
      get 'category/:id',          to: 'categories#show'
      get 'articles',              to: 'articles#index'
      get 'article/:id',           to: 'articles#show'
      get 'articles/title/:title', to: 'articles#search_by_title'
   end

   get 'home',        to: 'home/index#index'
   get 'news',        to: 'home/article#news'
   get 'notices',     to: 'home/article#notices'
   get 'products',    to: 'home/article#products'
   get 'article/:id', to: 'home/article#show',    as: 'article'
   get 'product/:id', to: 'home/article#product', as: 'product'
   get 'albums',      to: 'home/album#list',      as: 'albums'
   get 'album/:id',   to: 'home/album#show',      as: 'album'
   get 'about-us',    to: 'home/page#about_us'
   get 'contract-us', to: 'home/page#contract_us'

end

app/models/admin/article.rb
class Admin::Article < ActiveRecord::Base

	belongs_to :category
	has_many :article_picture, dependent: :destroy
	acts_as_paranoid	#for soft delete

	validates :title, presence: true
	validates :category_id, presence: true
	validates :author, presence: true
	validates :content, presence: true
	has_attached_file :thumb, 
					  styles: { small: "150x150>"},
					  url: "/uploads/articles/thumb/:id/:style/:basename.:extension",
					  path: ":rails_root/public/uploads/articles/thumb/:id/:style/:basename.:extension"
	validates_attachment :thumb, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	has_attached_file :file, 
					  url: "/uploads/articles/file/:id/:style/:basename.:extension",
					  path: ":rails_root/public/uploads/articles/file/:id/:style/:basename.:extension"
	validates_attachment :file, 
				  	content_type: { content_type:["application/pdf",															    #pdf
												  "application/msword",														    #doc
												  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",      #docx
												  "application/vnd.ms-excel",													    #excel
												  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",		    #xlsx
												  "application/vnd.ms-powerpoint",											    #ppt
												  "application/vnd.openxmlformats-officedocument.presentationml.presentation",    #pptx
												  "application/zip",															    #zip
												  "application/x-shockwave-flash"												    #swf
												   ]}

	scope :news_for_home,     -> { where(category_id: 2).limit(10).order('id asc') }	
	scope :notices_for_home,  -> { where(category_id: 3).limit(10).order('id asc') }	
	scope :products_for_home, -> { where(category_id: 5).limit(5).order('id asc') }	
	scope :news_for_list,     -> { where(category_id: 2).order('id asc') }	
	scope :notices_for_list,  -> { where(category_id: 3).order('id asc') }	
	scope :products_for_list, -> { where(category_id: 5).order('id asc') }										

end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
	has_ancestry
	has_many :article, dependent: :destroy

	validates :title, presence: true 

	scope :select_article_categories, -> { where(is_article: true) }
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AuthController
  before_action :set_admin_article, only: [:show, :edit, :update, :destroy]

  
  # GET /admin/articles
  # GET /admin/articles.json
  def index
    get_categories
    @admin_articles = Admin::Article.all
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
  end

  # GET /admin/articles/new
  def new
    @admin_article = Admin::Article.new
    get_categories
  end

  # GET /admin/articles/1/edit
  def edit
    get_categories
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @admin_article = Admin::Article.new(admin_article_params)

    respond_to do |format|
      if @admin_article.save
        format.html { redirect_to @admin_article, notice: "#{t 'activerecord.successful.messages.article_created'}" }
        format.json { render :show, status: :created, location: @admin_article }
        # format.js { render :show, status: :created, location: @admin_article }
      else
        get_categories
        format.html { render :new }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
        # format.js { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @admin_article.update(admin_article_params)
        format.html { redirect_to @admin_article, notice: "#{t 'activerecord.successful.messages.article_updated'}" }
        format.json { render :show, status: :ok, location: @admin_article }
      else
        get_categories
        format.html { render :edit }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @admin_article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: "#{t 'activerecord.successful.messages.article_deleted'}" }
      format.json { head :no_content }
    end
  end

  def article_concat
    @article_concat = Admin::Category.find(params[:id])
    render json: @article_concat
  end

  def multi_destroy
    respond_to do |format|
      if params[:article_ids] == nil
        format.html { redirect_to admin_articles_url, flash: { error: "#{t 'activerecord.error.messages.article_muti_deleted'}" }  }
        format.json { head :no_content }
      else
        Admin::Article.destroy(params[:article_ids])
        format.html { redirect_to admin_articles_url, notice: "#{t 'activerecord.successful.messages.article_muti_deleted'}" }
        format.json { head :no_content }
      end
    end
  end


  private
    def get_categories
      @categories = Admin::Category.select_article_categories 
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_article
      @admin_article = Admin::Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_article_params
      params.require(:admin_article).permit(:title, :category_id, :author, :is_recommand, :is_carousel, :is_mark, :content, :options, :abstract, :thumb, :file, :hits)
    end
end

app/controllers/admin/trash/articles_controller.rb
class Admin::Trash::ArticlesController < ApplicationController
  def index
  	@admin_trush_articles = Admin::Article.only_deleted
  end

  def restore
  	Admin::Article.restore(params[:id])
  	redirect_to admin_articles_url, notice: "#{t 'activerecord.successful.messages.article_restored'}"
  end

  def destroy
  	article = Admin::Article.only_deleted.find(params[:id])
    article.really_destroy!
  	redirect_to admin_trash_articles_url, notice: "#{t 'activerecord.successful.messages.article_force_deleted'}" 
  end

  def multi_destroy
    respond_to do |format|
      if params[:article_ids] == nil
        format.html { redirect_to admin_trash_articles_url, flash: { error: "#{t 'activerecord.error.messages.article_muti_deleted'}" }  }
        format.json { head :no_content }
      else  
        articles = Admin::Article.only_deleted.find(params[:article_ids])
        articles.each do |article|
          article.really_destroy!
        end
        format.html { redirect_to admin_trash_articles_url, notice: "#{t 'activerecord.successful.messages.article_muti_deleted'}" }
        format.json { head :no_content }
      end
    end
  end

end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController

	api :GET, '/articles', "get all articles"
	example " [{
				id: 2,
				category_id: 2,
				title: '测试新闻',
				author: '管理员',
				is_recommand: false,
				is_carousel: false,
				is_mark: false,
				options: '{}',
				content: '<p>测试新闻</p> ',
				abstract: '',
				hits: 0,
				created_at: '2015-03-27T15:17:42.000+08:00',
				updated_at: '2015-03-27T15:17:42.000+08:00',
				deleted_at: null,
				thumb_file_name: null,
				thumb_content_type: null,
				thumb_file_size: null,
				thumb_updated_at: null,
				file_file_name: null,
				file_content_type: null,
				file_file_size: null,
				file_updated_at: null
			},{...}] "
	def index
		begin
			@articles = Admin::Article.all
		rescue Exception => e
			render nothing: true 
		else
			render json: @articles 
		end
	end

	api! "get article by specificy id"
	param :id, String, :desc => "article ID", :required => true
	example "
		{
			id: 3,
			category_id: 2,
			title: '测试新闻',
			author: '管理员',
			is_recommand: false,
			is_carousel: false,
			is_mark: false,
			options: '{}',
			content: '<p>这个在上面</p> ',
			abstract: '',
			hits: 0,
			created_at: '2015-03-27T15:18:01.000+08:00',
			updated_at: '2015-03-27T15:18:01.000+08:00',
			deleted_at: null,
			thumb_file_name: null,
			thumb_content_type: null,
			thumb_file_size: null,
			thumb_updated_at: null,
			file_file_name: null,
			file_content_type: null,
			file_file_size: null,
			file_updated_at: null
		}"
	def show
		begin
			@article = Admin::Article.find(params[:id])
		rescue Exception => e
			render nothing: true 
		else
			render json: @article 
		end
	end

	api! "search articles by title"
	param :title, String, :desc => "article title", :required => false
	example "
		{
			id: 3,
			category_id: 2,
			title: '测试新闻',
			author: '管理员',
			is_recommand: false,
			is_carousel: false,
			is_mark: false,
			options: '{}',
			content: '<p>这个在上面</p> ',
			abstract: '',
			hits: 0,
			created_at: '2015-03-27T15:18:01.000+08:00',
			updated_at: '2015-03-27T15:18:01.000+08:00',
			deleted_at: null,
			thumb_file_name: null,
			thumb_content_type: null,
			thumb_file_size: null,
			thumb_updated_at: null,
			file_file_name: null,
			file_content_type: null,
			file_file_size: null,
			file_updated_at: null
		}"
	def search_by_title
		begin
			@articles = Admin::Article.where("title like ?", "%#{params[:title]}%")
		rescue Exception => e
			render nothing: true 
		else
			render json: @articles 
		end
		
	end
end

app/controllers/home/article_controller.rb
class Home::ArticleController < HomeController

	def news
		@articles = Admin::Article.news_for_list
		respond_to do |format|
			format.html { render :template => "home/list" }
		end
	end

	def notices
		@articles = Admin::Article.notices_for_list
		respond_to do |format|
			format.html { render :template => "home/list" }
		end
	end

	def products
		@articles = Admin::Article.products_for_list
		respond_to do |format|
			format.html { render :template => "home/list" }
		end
	end


	def show
		@article = Admin::Article.find(params[:id])
		respond_to do |format|
			format.html { render :template => "home/article" }
		end
	end

	def product
		@article = Admin::Article.find(params[:id])
		respond_to do |format|
			format.html { render :template => "home/product" }
		end
	end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/trash/articles_helper.rb
module Admin::Trash::ArticlesHelper
end

app/helpers/api/articles_helper.rb
module Api::ArticlesHelper
end

app/helpers/home/article_helper.rb
module Home::ArticleHelper
end

app/views/admin/articles/_basic_panel.html.erb
    <!-- widget-section-1 -->
    <div class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false">
      <header>
        <span class="widget-icon"><i class="fa fa-edit"></i></span>
        <h2><%= t("article.basic_info") %></h2>
      </header>

      <!-- smart-form -->
      <div class="smart-form">
        <div class="jarviswidget-editbox"></div>
        <!-- widget-body  -->
        <div class="widget-body no-padding">
          <!-- basic information -->
          <fieldset>
            <!-- title -->
            <div class="row">
              <section class="col col-6">
                <label class="label"> 
                  <%= f.label t("article.title")  %><br>
                </label>
                <label class="input">
                  <i class="icon-append fa fa-pencil"></i>
                  <%= f.text_field :title, required: true %>
                </label>
              </section>
            </div>
            <!-- end title -->
            <!-- category -->
            <div class="row">
              <% if @admin_article.created_at %>
                <section class="col col-4">
                <label class="label"> 
                  <%= f.label t("article.category") %><br>
                </label>
                <label class="input"><i class="icon-append fa fa-lock"></i>
                  <input type="text" value="<%= @admin_article.category.title %>" readonly >
                </label>
              </section>
              <% else %>
              <section class="col col-4">
                <label> 
                  <%= f.label t("article.category") %><br>
                </label>
                <select name="admin_article[category_id]" class="select2" id="article-category" required >
                  <option value="" disabled selected><%= t "article.select_option_default" %></option>
                  <% @categories.each do |article_category| %>
                  <option value="<%= article_category.id %>"><%= article_category.title %></option>
                  <% end %>
                </select>
              </section>
              <% end %>
            </div>
            <!-- end category -->

            <!-- author -->
            <div class="row">
              <section class="col col-3">
                <label class="label"> 
                  <%= f.label t("article.author") %><br>
                </label>
                <label class="input">
                  <i class="icon-append fa fa-pencil"></i>
                  <%= f.text_field :author, required: true%>
                </label>
              </section>
            </div>
            <!-- end author -->
            <!-- hits -->
            <div class="row">
              <section class="col col-1">
                <label><%= f.label t("article.hits") %></label>
                <%= f.text_field :hits, class: "spinner-both", id: "spinner", value: 0, style: 'box-sizing: border-box;', required: true %>
              </section>
            </div>
            <!-- end hits -->
            <!-- recommand switch -->
            <div class="row">
              <section class="col col-3">
                <label class="toggle">
                  <%= f.check_box :is_recommand %>
                  <i data-swchoff-text="关闭" data-swchon-text="开启"></i><%= f.label t("article.is_recommand") %>
                </label>
              </section>
            </div>
            <!-- end recommand switch -->
            <!-- carousel switch -->
            <div class="row">
              <section class="col col-3">
                <label class="toggle">
                  <%= f.check_box :is_carousel %>
                  <i data-swchoff-text="关闭" data-swchon-text="开启"></i><%= f.label t("article.is_carousel") %>
                </label>
              </section>
            </div>
            <!-- end carousel switch -->
            <!-- mark switch -->
            <div class="row">
              <section class="col col-3">
                <label class="toggle">
                  <%= f.check_box :is_mark %>
                  <i data-swchoff-text="关闭" data-swchon-text="开启"></i><%= f.label t("article.is_mark") %>
                </label>
              </section>
            </div>
            <!-- end mark switch -->
          </fieldset>
          <!-- end basic information -->   
        </div>
        <!-- end widget-body -->
      </div>
      <!-- end smart-form -->
    </div>
    <!-- end widget-section-1 -->

app/views/admin/articles/_content_panel.html.erb
<!-- widget-section-4 -->
<div class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" data-widget-fullscreenbutton="false" >
  <header>
    <span class="widget-icon"><i class="fa fa-edit"></i></span>
    <h2><%= t("article.content_info") %></h2>
  </header>
  <!-- smart-form -->
  <div class="smart-form">
    <fieldset>
      <!-- content -->
      <div class="row">
        <section> 
          <%= f.cktext_area :content, required: true, :ckeditor => {:language => 'zh-cn', :toolbar => 'Full' }  %>
        </section>
      </div>
      <!-- end content -->
    </fieldset>
    <!-- footer -->
    <footer>
      <%= link_to t("operate.back"), admin_articles_path, class: "btn btn-primary", data: { no_turbolink: true } %>
      <div class="actions">
        <%= link_to t("operate.submit"),"javascript:submit()", class: 'btn btn-primary' %>
      </div>
    </footer>
    <!-- end footer -->
  </div>
  <!-- end smart-form -->
</div>
<!-- end widget-section-4 -->

app/views/admin/articles/_error.html.erb
 <% if @admin_article.errors.any? %>
 <div id="error_explanation">
  <div class="alert alert-danger fade in">
    <button class="close" data-dismiss="alert">×</button>
    <i class="fa-fw fa fa-times"></i>
    <strong>
      <% @admin_article.errors.full_messages.each do |message| %>
      	<%= message %>
      <% end %>
    </strong>
  </div>
</div>
<% end %>

app/views/admin/articles/_option_list_for_edit.html.erb
<% eval(@admin_article.options).each_slice(2) do |slice| %>
<div class='row'>
	<% slice.each do |key,value| %>
	<section class="col col-4">
		<label for="<%= key %>" class="label"><%= key %></label>
		<label class="input"><i class='icon-append fa fa-cogs'></i>
			<input type="text" name="<%= key %>" value="<%= value %>" >
		</label>
	</section>
	<% end %>
</div>
<% end %>

app/views/admin/articles/_option_panel.html.erb
     <!-- widget-section-2 -->
    <div class="jarviswidget jarviswidget-color-darken" data-widget-editbutton="false" id="option_panel">
      <header>
        <span class="widget-icon"><i class="fa fa-edit"></i></span>
        <h2><%= t("article.option_info") %></h2>
      </header>
      <!-- smart-form -->
      <div class="smart-form">
        <!-- extra information -->
        <fieldset>
           <!-- option -->
          <%= f.hidden_field :options, id: "options" %>
          <div class="row" id="is_option">
            <section class="col col-8"> 
              <div class="div" id="option_items">
                <% if @admin_article.options %>
                <%= render partial: "option_list_for_edit", locals: {admin_article: @admin_article} %>
                <% else %>
                <%= t "article.select_option_default" %>
                <% end %>
              </div>
            </section>
          </div>
          <!-- end option -->
        </fieldset> 
        <!-- end extra information    -->
      </div>
      <!-- end smart-form -->
    </div>
    <!-- end widget-section-2 -->

app/views/admin/articles/index.html.erb
<%if notice %>
<div class="alert alert-success fade in">
  <button class="close" data-dismiss="alert">×</button>
  <i class="fa-fw fa fa-check"></i>
  <strong><%= notice %></strong>
</div>
<% end %>
<%if flash[:error] %>
<div class="alert alert-danger fade in">
  <button class="close" data-dismiss="alert">×</button>
  <i class="fa-fw fa fa-times"></i>
  <strong><%= flash[:error] %></strong>
</div>
<% end %>
<%= form_tag multi_destroy_admin_articles_path, method: :delete, id: "muti_destory_form"  do %>
<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
  <header>
    <span class="widget-icon"> <i class="fa fa-file"></i> </span>
    <h2><p><%= t("article.table_title") %></p></h2>
  </header>
  <div>
    <div class="jarviswidget-editbox"></div>  
    <div class="widget-body no-padding">
      <table id="datatable_fixed_column" class="table table-bordered">
        <thead>
          <tr>
            <th> <!-- fix for id --> </th>
            <th><%= t("article.id") %></th>
            <th><%= t("article.title") %></th>
            <th><%= t("article.author") %></th>
            <th><%= t("article.hits") %></th>
            <th><%= t("article.created_at") %></th> 
            <th><%= t("article.category") %></th>
            <th><%= t("operate.title") %></th>
          </tr>
          <tr class="second">
            <td colspan="2">
              <!-- fix for search init -->
              <input type="text" class="search_init hidden"></div><input type="text" class="search_init hidden"></div>
              <%= link_to t("operate.delete_selected"),"javascript:mutiDestroy()", class: 'btn bg-color-red txt-color-white' %>
            </td>
            <td class="smart-form">
              <label class="input">
                <input type="text" value="<%= t("article.search_by_title") %>" class="search_init">
              </label>  
            </td>
             <td class="smart-form">
              <label class="input">
                <input type="text" value="<%= t("article.search_by_author") %>" class="search_init">
              </label>  
            </td>
             <td class="smart-form">
              <label class="input">
                <input type="text" value="<%= t("article.search_by_hits") %>" class="search_init">
              </label>  
            </td>
            <td class="smart-form">
               <label class="input"><i class="icon-append fa fa-calendar"></i>
                <input type="text" value="<%= t("article.search_by_created") %>" class="datepicker search_init" data-dateformat="yy-mm-dd">
              </label>
            </td>
            <td class="smart-form">
              <label class="input">
               <select id="category_select" class="select2">
                <option value="" selected><%= t "article.select_option_all" %></option>
                <% @categories.each do |article_category| %>
                <option value="<%= article_category.title %>"><%= article_category.title %></option>
                <% end %>
              </select>
            </label>  
          </td>
            <td>
              <%= link_to t("operate.new"), new_admin_article_path, data: { no_turbolink: true }, class: "btn bg-color-green txt-color-white" %>
            </td>
          </tr>
        </thead>

        <tbody>
          <% @admin_articles.each do |admin_article| %>
          <tr>
            <td class="smart-form"><label class="checkbox"><%= check_box_tag "article_ids[]", admin_article.id %><i></i> </label></td>
            <td><%= admin_article.id %></td>
            <td><%= admin_article.title %></td>
            <td><%= admin_article.author %></td>
            <td><%= admin_article.hits %></td>
            <td><%= admin_article.created_at.strftime("%Y-%m-%d") %></td>
            <td><%= admin_article.category.title %></td>
            <td>
             <%= link_to t("operate.show"), admin_article, class: "btn bg-color-blue txt-color-white" %>
             <%= link_to t("operate.edit"), edit_admin_article_path(admin_article), data: { no_turbolink: true }, class: "btn bg-color-orange txt-color-white" %>
             <%= link_to t("operate.delete"), admin_article, method: :delete, data: { title: "#{t('article.delete_title')}", confirm: "#{t('article.delete_info')}" }, class: "btn bg-color-red txt-color-white" %>
             <%= link_to t("article.is_carousel"), picture_by_admin_article_picture_path(admin_article.id), class: "btn bg-color-blueDark txt-color-white" if admin_article.category.is_carousel %>
           </td>
         </tr>
         <% end %>
       </tbody>
     </table>      
   </div>
 </div>
</div>
<% end %>

app/views/admin/articles/show.html.erb
<%if notice %>
<div class="alert alert-success fade in">
  <button class="close" data-dismiss="alert">×</button>
  <i class="fa-fw fa fa-check"></i>
  <strong><%= notice %></strong>
</div>
<% end %>
<div class="jarviswidget jarviswidget-color-darken" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
  <header>
    <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
    <h2><%= t("operate.show") %></h2>        
  </header>
  <div>
    <div class="jarviswidget-editbox"></div>
    <div class="widget-body">
      <div class="smart-form">
        <fieldset>
          <div class="row">
            <section class="col col-md-12">
              <h2 class="text-center">
                <%= @admin_article.title %>
              </h2>
            </section>
          </div>
          <div class="row">
            <section class="col col-md-12">
              <h5 class="text-right"><%= t("article.author") %>:
              <%= @admin_article.author %>&nbsp;
                <%= t("article.created_at") %>:
                <%= @admin_article.created_at.strftime("%Y-%m-%d") %>&nbsp;
                <%= t("article.hits") %>:
                <%= @admin_article.hits %>
              </h5>
            </section>
          </div>

           <div class="row">
            <section class="col col-md-12">
               <h2 class="article-abstract">
                <small><%= @admin_article.abstract %></small>
              </h2>
            </section>
          </div>
          <% if @admin_article.options %>
          <div class="row">
            <section class="col col-md-12">
              <h2 class="article-option">
                <% eval(@admin_article.options).each do |key,value| %>
                <div class="col-md-1"><small><%= key %>：</small></div>
                <div class="col-md-1"><small><%= value %></small></div>
                <% end %>
              </h2>
            </section>
          </div>
          <% end %>
          <div class="row">
            <section class="col col-md-12">
              <h5 class="article-content">
                <%= raw(@admin_article.content) %>
              </h5>
            </section>
          </div>

          <% if (@admin_article.thumb_file_name) %>
           <div class="row">
            <section class="col col-md-12">
              <span class="article-thumb"><i class="glyphicon glyphicon-picture"></i><%= t("article.thumb") %>:</span>
            </section>
            <section class="col col-md-12">
              <%= image_tag @admin_article.thumb.url(:small) %>
            </section>
          </div>
          <% end %>

          <% if (@admin_article.file_file_name) %>
           <div class="row">
            <section class="col col-md-12">
              <span class="article-link pull-right"><i class="glyphicon glyphicon-link"></i><%= t("article.file") %>:
              <a href="<%= @admin_article.file.url %>"><%= @admin_article.file_file_name %></a>
              </span>
            </section>
          </div>
          <% end %>

        </fieldset>
        <footer>
          <%= link_to t("operate.back"), admin_articles_path, class: "pull-right btn btn-primary", data: { no_turbolink: true } %>
          <%= link_to t("operate.edit"), edit_admin_article_path(@admin_article), class: "pull-right btn btn-primary", data: { no_turbolink: true }%>
        </footer>
      </div>
    </div>
    <!-- end widget content -->
  </div>
  <!-- end widget div -->
</div>