config/routes.rb
Rails.application.routes.draw do


  apipie
  root to: 'admin/home#index'

  devise_for :users, 
             controllers: { sessions: "users/sessions" }, 
             path: "", 
             path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

  #menu 
    resources :menus, path: 'menu', except: :new do
        #add a category under super category.
        get 'new', to: 'menus#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

  #banner
    resources :banners, path: 'banner'
  #links
    resources :links, path: 'link'


  #article module
    resources :categories, path: 'category', except: :new do
        #add a category under super category.
        get 'new', to: 'categories#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

    resources :articles, path: 'article' do
        #reload article elements when categroy select changed.
        get 'concat', to: 'articles#article_concat', on: :collection
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
    end
    resources :article_options, path: 'article-option'
    resources :article_pictures, path: 'article-picture', only: [:create, :destroy] do
      #show pictures belongs specificy article.
      get '',  to: 'article_pictures#index', 
               as: :picture_by, 
               constraints: { article_id: /\d/ },
               on: :member  
    end
  #album module
    resources :album_tags, path: 'album-tags'
    resources :albums
    resources :photos, except: :new do
      get 'new', to: 'photos#new', 
                 as: :photo_new, 
                 :constraints => { :parent_id => /\d|nil/ },
                 on: :member
    end

  #page module
    resources :pages, path: 'page'
    
  #trash module
    namespace :trash do
      #for article
      resources :articles, path: 'article', only: [:index, :destroy] do
        put 'restore', to: 'articles#restore', on: :member
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
      end
      #for pages
      resources :pages, path: 'page', only: [:index, :destroy] do
        put 'restore', to: 'pages#restore', on: :member
      end
    end
    #end trash namespae
    
    #message module
    resources :messages, path: 'message' do
      put 'review', to: 'messages#review', on: :member
    end

    get 'visit', to: 'statistics#index', as: 'visit'

  end 
  #end admin namespace

   namespace :api do
      # api for layouts
      get 'menus',                 to: 'layouts#menus'
      get 'link',                  to: 'layouts#friend_links'
      get 'categories',            to: 'categories#index'
      get 'category/:id',          to: 'categories#show'
      get 'articles',              to: 'articles#index'
      get 'article/:id',           to: 'articles#show'
      get 'articles/title/:title', to: 'articles#search_by_title'
   end

   get 'home',        to: 'home/index#index'
   get 'news',        to: 'home/article#news'
   get 'notices',     to: 'home/article#notices'
   get 'products',    to: 'home/article#products'
   get 'article/:id', to: 'home/article#show',    as: 'article'
   get 'product/:id', to: 'home/article#product', as: 'product'
   get 'albums',      to: 'home/album#list',      as: 'albums'
   get 'album/:id',   to: 'home/album#show',      as: 'album'
   get 'about-us',    to: 'home/page#about_us'
   get 'contract-us', to: 'home/page#contract_us'

end

app/controllers/api/layouts_controller.rb
class Api::LayoutsController < ApplicationController

	api! "get site menus"
	example "
	[{
		ancestry: null,
		id: 21,
		name: 'HOME',
		url: '/test',
		weight: 1,
		visible: true,
		children: [ ]
	},{
		ancestry: null,
		id: 2,
		name: 'NEWS',
		url: '/news',
		weight: 2,
		visible: true,
		children: [ ]
	},{ ... 
	}]"
	def menus
		@menus = Admin::Menu.all_by_order.arrange_serializable(order: :weight)
		render json: @menus 
	end

	api :GET, "/firend-link", "get friend links"
	example "
	[{
		ancestry: null,
		id: 21,
		name: 'HOME',
		url: '/test',
		weight: 1,
		visible: true,
		children: [ ]
	},{
		ancestry: null,
		id: 2,
		name: 'NEWS',
		url: '/news',
		weight: 2,
		visible: true,
		children: [ ]
	},{ ... 
	}]"
	def friend_links
		@firend_links = Admin::FriendLink.all
		render json: @firend_links
	end
end

app/helpers/api/layouts_helper.rb
module Api::LayoutsHelper
end

app/views/layouts/admin/_aside.html.erb
<aside id="left-panel">
	<nav>
		<ul>
			<li>
				<a href="<%= root_path %>"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">	
					<%= t("menu.submenu.home_menu") %>
				</span></a>
			</li>
			<li>
				<a href="#"><i class="fa fa-lg fa-fw fa-sitemap"></i> <span class="menu-item-parent">	
					<%= t("menu.submenu.site_menu") %>
				</span></a>
				<ul>
					<li><%= link_to t("menu.midmenu.menu_menu"), admin_menus_path %></li>
					<li><%= link_to t("menu.midmenu.link_menu"), admin_links_path %></li>
					<li><%= link_to t("menu.midmenu.banner_menu"), admin_banners_path %></li>
					<li><%= link_to t("menu.midmenu.page_menu"), admin_pages_path %></li>
					<li><%= link_to t("menu.midmenu.visit_menu"), admin_visit_path %></li>
				</ul>
			</li>
			<li>
				<a href="#"><i class="fa fa-lg fa-fw fa-list-ul"></i> <span class="menu-item-parent">
					<%= t("menu.submenu.article_menu") %>
				</span></a>
				<ul>
					<li><%= link_to t("menu.midmenu.category_menu"), admin_categories_path %></li>
					<li><%= link_to t("menu.midmenu.article_option"), admin_article_options_path %></li>
					<li><%= link_to t("menu.midmenu.article_menu"), admin_articles_path %></li>
				</ul>
			</li>
			<li>
				<a href="#"><i class="fa fa-lg fa-fw fa-picture-o"></i> <span class="menu-item-parent">
					<%= t("menu.submenu.album_menu") %>
				</span></a>
				<ul>
					<li><%= link_to t("menu.midmenu.album_tags"), admin_album_tags_path %></li>
					<li><%= link_to t("menu.midmenu.album"), admin_albums_path %></li>
				</ul>
			</li>
			<li>
				<a href="#"><i class="fa fa-lg fa-fw fa-comments"></i> <span class="menu-item-parent">
					<%= t("menu.submenu.message_menu") %>
				</span></a>
				<ul>
					<li><%= link_to t("menu.midmenu.message_menu"), admin_messages_path %></li>
				</ul>
			</li>
			<li>
				<a href="#"><i class="fa fa-lg fa-fw fa-trash-o"></i> <span class="menu-item-parent">
					<%= t("menu.submenu.trash_menu") %>
				</span></a>
				<ul>
					<li><%= link_to t("menu.midmenu.trash_article"), admin_trash_articles_path %></li>
					<li><%= link_to t("menu.midmenu.trash_page"), admin_trash_pages_path %></li>

				</ul>
			</li>
		</ul>
	</nav>
	<span class="minifyme"> <i class="fa fa-arrow-circle-left hit"></i> </span>
</aside>