config/routes.rb
Rails.application.routes.draw do


  apipie
  root to: 'admin/home#index'

  devise_for :users, 
             controllers: { sessions: "users/sessions" }, 
             path: "", 
             path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

  #menu 
    resources :menus, path: 'menu', except: :new do
        #add a category under super category.
        get 'new', to: 'menus#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

  #banner
    resources :banners, path: 'banner'
  #links
    resources :links, path: 'link'


  #article module
    resources :categories, path: 'category', except: :new do
        #add a category under super category.
        get 'new', to: 'categories#new', 
                   on: :member, 
                   as: :new, 
                   :constraints => { :parent_id => /\d/ }
    end

    resources :articles, path: 'article' do
        #reload article elements when categroy select changed.
        get 'concat', to: 'articles#article_concat', on: :collection
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
    end
    resources :article_options, path: 'article-option'
    resources :article_pictures, path: 'article-picture', only: [:create, :destroy] do
      #show pictures belongs specificy article.
      get '',  to: 'article_pictures#index', 
               as: :picture_by, 
               constraints: { article_id: /\d/ },
               on: :member  
    end
  #album module
    resources :album_tags, path: 'album-tags'
    resources :albums
    resources :photos, except: :new do
      get 'new', to: 'photos#new', 
                 as: :photo_new, 
                 :constraints => { :parent_id => /\d|nil/ },
                 on: :member
    end

  #page module
    resources :pages, path: 'page'
    
  #trash module
    namespace :trash do
      #for article
      resources :articles, path: 'article', only: [:index, :destroy] do
        put 'restore', to: 'articles#restore', on: :member
        delete 'multi-destroy', to: 'articles#multi_destroy', on: :collection
      end
      #for pages
      resources :pages, path: 'page', only: [:index, :destroy] do
        put 'restore', to: 'pages#restore', on: :member
      end
    end
    #end trash namespae
    
    #message module
    resources :messages, path: 'message' do
      put 'review', to: 'messages#review', on: :member
    end

    get 'visit', to: 'statistics#index', as: 'visit'

  end 
  #end admin namespace

   namespace :api do
      # api for layouts
      get 'menus',                 to: 'layouts#menus'
      get 'link',                  to: 'layouts#friend_links'
      get 'categories',            to: 'categories#index'
      get 'category/:id',          to: 'categories#show'
      get 'articles',              to: 'articles#index'
      get 'article/:id',           to: 'articles#show'
      get 'articles/title/:title', to: 'articles#search_by_title'
   end

   get 'home',        to: 'home/index#index'
   get 'news',        to: 'home/article#news'
   get 'notices',     to: 'home/article#notices'
   get 'products',    to: 'home/article#products'
   get 'article/:id', to: 'home/article#show',    as: 'article'
   get 'product/:id', to: 'home/article#product', as: 'product'
   get 'albums',      to: 'home/album#list',      as: 'albums'
   get 'album/:id',   to: 'home/album#show',      as: 'album'
   get 'about-us',    to: 'home/page#about_us'
   get 'contract-us', to: 'home/page#contract_us'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AuthController
	def index
	end
end

app/controllers/home/album_controller.rb
class Home::AlbumController < HomeController
	
	def list
		@albums = Admin::Album.all
		respond_to do |format|
			format.html { render :template => "home/album" }
		end		
	end

	def show
		@album = Admin::Album.find(params[:id])
		@photos = Admin::Photo.where("album_id = ?", params[:id])
		# @photos = Admin::Photo.photos_for_album(params[:id])
		respond_to do |format|
			format.html { render :template => "home/photo" }
		end
	end
end

app/controllers/home/article_controller.rb
class Home::ArticleController < HomeController

	def news
		@articles = Admin::Article.news_for_list
		respond_to do |format|
			format.html { render :template => "home/list" }
		end
	end

	def notices
		@articles = Admin::Article.notices_for_list
		respond_to do |format|
			format.html { render :template => "home/list" }
		end
	end

	def products
		@articles = Admin::Article.products_for_list
		respond_to do |format|
			format.html { render :template => "home/list" }
		end
	end


	def show
		@article = Admin::Article.find(params[:id])
		respond_to do |format|
			format.html { render :template => "home/article" }
		end
	end

	def product
		@article = Admin::Article.find(params[:id])
		respond_to do |format|
			format.html { render :template => "home/product" }
		end
	end

end

app/controllers/home/index_controller.rb
class Home::IndexController < HomeController
	
	def index
		@news = Admin::Article.news_for_home
		@notices = Admin::Article.notices_for_home
		@products = Admin::Article.products_for_home
		@albums = Admin::Album.albums_for_home
	end
end

app/controllers/home/page_controller.rb
class Home::PageController < HomeController

	def about_us
		@page = Admin::Page.about_us
		respond_to do |format|
			format.html { render template: "home/page" }
		end
	end


	def contract_us
		@page = Admin::Page.contract_us
		respond_to do |format|
			format.html { render template: "home/page" }
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	#render to specificy layout.
	layout 'home'

	#set conmmon variable for each views.
	before_filter :set_layout_variable
	
	def set_layout_variable
		@menus = Admin::Menu.all_by_order
		@banners = Admin::Banner.all
		@friend_links = Admin::Link.all
	end
	
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home/album_helper.rb
module Home::AlbumHelper
end

app/helpers/home/article_helper.rb
module Home::ArticleHelper
end

app/helpers/home/index_helper.rb
module Home::IndexHelper
end

app/helpers/home/page_helper.rb
module Home::PageHelper
end

app/views/home/album.html.erb
<div id="cms-album">
	<% @albums.each do |album| %>
	<div class="row text-center">
		<a href="<%= album_path(album.id) %>"><%= image_tag album.cover.url(:small) %></a>
		<h4><%= album.name %></h4>
		<p><%= album.description %></p>
	</div>
	<% end %>
</div>

app/views/home/article.html.erb
<div id="cms-article">
	<div class="row">
		<h3><%= @article.title %></h3>
	</div>
	<div class="row">
		<div class="cms-article-content">
			<%= sanitize @article.content %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div id="cms-index">
	<div class="row">
		<div class="col-md-6">
			<h3>News<small><a href="<%= news_path %>">more</a></small></h3>
			<% @news.each do |news| %>
			<h5>
				<p>
					<a href="<%= article_path(news.id) %>"><%= news.title %></a>
					<small><%= news.created_at.strftime("%Y/%m/%d") %></small>
				</p>
			</h5>
			<% end %>
		</div>
		<div class="col-md-6">
			<h3>Notices<small><a href="<%= notices_path %>">more</a></small></h3>
			<% @notices.each do |notice| %>
			<h5>
				<p>
					<a href="<%= article_path(notice.id) %>"><%= notice.title %></a>
					<small><%= notice.created_at.strftime("%Y/%m/%d") %></small>
				</p>
			</h5>
			<% end %>
		</div>
	</div>
	<br><br>
	<div class="row">
		<div class="col-md-6">
			<h3>Products<small><a href="<%= products_path %>">more</a></small></h3>
			<% @products.each do |product| %>
			<div class="col-md-6 text-center">
				<p>
					<a href="<%= article_path(product.id) %>"><%= image_tag "/images/no-image.png", class: "text-center" %></a>
				</p>
				<p class="text-center"><%= product.title %></p>
			</div>
			<% end %>
		</div>
		<div class="col-md-6">
			<h3>Albums<small><a href="<%= albums_path %>">more</a></small></h3>
			<% @albums.each do |album| %>
			<div class="col-md-6 text-center">
				<a href="<%= album_path(album.id) %>"><%= image_tag "/images/no-image.png", class: "text-center" %></a>
				<p class="text-center"><%= album.name %></p>
			</div>
			<% end %>
		</div>
	</div>

</div>

app/views/home/list.html.erb
<div id="cms-list">
	<% @articles.each do |article| %>
	<div class="row">
		<h4><a href="<%= article_path(article.id) %>"><%= article.title %></a></h4>
		<%= image_tag article.thumb.url(:small) if article.thumb_file_name %>
		<p><%= article.abstract %></p>
		<hr>
	</div>
	<% end %>
</div>

app/views/home/page.html.erb
<div id="cms-page">
	<div class="row text-center">
		<h3><%= @page.title %></h3>
	</div>
	<div class="row">
		<%= sanitize @page.content %>
	</div>	
</div>

app/views/home/photo.html.erb
<div id="cms-photo">
	<% @photos.each do |photo| %>
	<div class="row text-center">
	<%= image_tag  photo.image.url %>
	</div>
	<% end %>
</div>

app/views/home/product.html.erb
This is product page~